spring:
  artemis:
    broker-url: tcp://0.0.0.0:61616 
    mode: native
    password: admin
    user: admin 
#app mode

app:
  patientQueue: patientQueue
  notificationQueue: notificationQueue
server:
  port: 8089